# Generated by Django 2.1.1 on 2018-09-27 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20180927_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_dat',
            new_name='article_date',
        ),
    ]
